### ISSUE TITLE
Add Event Notificator class to Fueled utils

### ISSUE THREAD

**Issue by ghost** [Fueled/ios-utilities#8]
Event Notificator implements a common pattern used across different teams and projects.
The key benefit is that is completes the signal it aggregates on deallocation ridding the app's state of potentially unused subscriptions. It also makes client code more concise.

```swift
//
//  Created by Ivan Korepanov on 29/09/2017.
//  Copyright © 2017 Fueled. All rights reserved.
//

import Foundation
import ReactiveSwift
import Result

final class EventNotificator<T> {
	let signal: Signal<T, NoError>
	private let observer: Signal<T, NoError>.Observer

	init() {
		(self.signal, self.observer) = Signal<T, NoError>.pipe()
	}

	func notify(message: T) {
		self.observer.send(value: message)
	}

	deinit {
		self.observer.sendCompleted()
	}
}
```

**Comment by ghost** [comment]
What it does remove though is, interface segregation: whoever sees the `signal`, can call `notify(message:)`. Normally, the observer is private to the class exposing the signal.

**Comment by bastien-fueled** [comment]
Yes that sounds like a blocker to me ^. I don't want the outside world to be able to send a signal, the `observer` should be totally private to the class expositing the signal 😕

**Comment by ivan-fueled** [comment]
It's a just a wrapper for signal-observer pair which we use pretty often in our projects, you can expose only signal of a notificator object not notificator itself.

**Comment by ghost** [comment]
Looks like the problem it solves is not actually a problem and deallocation of the observer will terminate the signal anyway. There's no need to complete it manually.

**Comment by ivan-fueled** [comment]
@leontiy, @bastien-fueled 
1. `Completed` event is never sent if to not do it in the deinitializer. - I think it's a bad practice.
2. I'm too lazy to write this boilerplate again and again. 
3. You can always make the notificator private and expose only signal from it.

**Comment by leonty-fueled** [comment]
> Completed event is never sent if to not do it in the deinitializer. - I think it's a bad practice.
@ivan-fueled why do you think that?

**Comment by ghost** [comment]
Ok, I closed this discussion prematurely. So the informal contract requirement is that any signal ends with either Failed, Interrupted or Completed event. In case of not sending completed manually to a pipe, the signal is still disposed of when the observer is deallocated but the contract requirement is not fulfilled, so it's looks advisable to include a helper like this.

**Comment by ghost** [comment]
Because it's not very easy to test in a playground, I've asked a question in reactiveswift Slack channel: https://reactiveswift.slack.com/archives/C3EAYH43B/p1507545970000117
If someone could test this in an app setting, it would be great!

**Comment by ivan-fueled** [comment]
@leonty-fueled It sends `interrupted` in the case of not sending completed.

**Comment by leontiy** [comment]
Then there's no problem to solve here, right @ivan-fueled? The contract of the signal appears to be fulfilled automatically.

**Comment by leontiy** [comment]
Or is there any other reason to consider not sending completed manually a bad practice?

**Comment by heymansmile** [comment]
@leontiy I've just re-read your opening comment for this theme: 
_The key benefit is that is completes the signal it aggregates on deallocation ridding the app's state of potentially unused subscriptions. It also makes client code more concise._
The key benefit was to get rid of creating the boilerplate every time) Completing the signal is a bonus which is performed just because "we can" do it in an appropriate moment;)

**Comment by heymansmile** [comment]
^ it wasn't me who unassigned all the guys ¯\_(ツ)_/¯.

**Comment by leontiy** [comment]
@ivan-fueled Do we agree that the issue was not really an issue?

**Comment by heymansmile** [comment]
@leontiy as I mentioned above: I created this class not in order to fix any issues but just because of my laziness of writing a lot of identical code every time:)

**Comment by leontiy** [comment]
Yeah, but the reason to write it was that that you wanted to complete your pipes instead of interrupting them. I think we now agree that it's an unnecessary ask for a pipe signal in general, don't we?

**Comment by heymansmile** [comment]
@leontiy it never was the reason to write this (from my side)) As far as I remember the conversation about completing/interrupting started after you created the very first description for this class at the very top of this page ;)

**Comment by leontiy** [comment]
ok, so as far as I can tell, this class does not solve any specific problem apart from a minor syntactic simplification for untyped notifications. Therefore I take the responsibility to declare this an uncommon use case and close the issue without adding the component to the library.

**Comment by heymansmile** [comment]
@leontiy sure it definitely can be closed, I didn't create this github issue:)
